# Generated by Django 4.1.3 on 2022-11-11 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server_app', '0004_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=2000)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_app.staff')),
            ],
        ),
    ]
