# Generated by Django 4.1.3 on 2022-11-11 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0002_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('Test_id', models.AutoField(primary_key=True, serialize=False)),
                ('Test_name', models.CharField(max_length=250)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Question_id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField(max_length=500)),
                ('Option1', models.CharField(max_length=250)),
                ('Option2', models.CharField(max_length=250)),
                ('Option3', models.CharField(max_length=250)),
                ('Option4', models.CharField(max_length=250)),
                ('Correct_Ans', models.CharField(max_length=250)),
                ('Test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.test')),
            ],
        ),
    ]
