# Generated by Django 4.1.3 on 2022-11-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0003_test_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Test_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
