# Generated by Django 4.1.3 on 2022-11-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0004_alter_test_test_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Question',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
