# Generated by Django 4.1.3 on 2022-11-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0004_course'),
        ('cources', '0005_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cources.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_app.student')),
            ],
        ),
    ]
