# Generated by Django 4.1.3 on 2022-11-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0006_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigned',
            old_name='id',
            new_name='Assigned_id',
        ),
    ]
