# Generated by Django 4.1.3 on 2022-11-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0007_rename_id_assigned_assigned_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='Course',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='Student',
            field=models.CharField(max_length=25),
        ),
    ]
