# Generated by Django 4.1.3 on 2022-11-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cources', '0008_alter_assigned_course_alter_assigned_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='Course',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='Student',
            field=models.IntegerField(),
        ),
    ]
