# Generated by Django 4.1.3 on 2022-11-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0002_staff_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=75)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Field_of_study', models.CharField(max_length=100)),
                ('isActive', models.BooleanField(default=True)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
