# Generated by Django 4.1.3 on 2022-11-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_app', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
